apiVersion: v1
kind: Namespace
metadata:
  name: vllm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models
  namespace: vllm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: oci-bv
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: hf-token-secret
  namespace: vllm
type: Opaque
data:
  token: "<base64-HF-token>"
