apiVersion: v1
kind: Service
metadata:
  name: {{ include "triton.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "triton.labels" . | nindent 4 }}
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
spec:
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  selector:
    {{- include "triton.selectorLabels" . | nindent 4 }}
