apiVersion: v1
kind: Service
metadata:
  name: {{ include "triton.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "triton.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-inference-server
      port: {{ .Values.service.ports.http }}
      targetPort: http
    - name: grpc-inference-server
      port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
    - name: metrics-inference-server
      port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
  selector:
    {{- include "triton.selectorLabels" . | nindent 4 }}
