apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "triton.fullname" . }}-metrics-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "triton.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "triton.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 15s
